# Makefile.in generated automatically by automake 1.4a from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/gmp
pkglibdir = $(libdir)/gmp
pkgincludedir = $(includedir)/gmp

top_builddir = ../..

ACLOCAL = ${SHELL} /home/sverker/agents/gmp/missing --run aclocal
AUTOCONF = ${SHELL} /home/sverker/agents/gmp/missing --run autoconf
AUTOMAKE = ${SHELL} /home/sverker/agents/gmp/missing --run automake
AUTOHEADER = ${SHELL} /home/sverker/agents/gmp/missing --run autoheader

INSTALL = /usr/gnu/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_FLAG =
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :


build_alias = sparcv9-sun-solaris2.7
build_triplet = sparcv9-sun-solaris2.7
host_alias = sparcv9-sun-solaris2.7
host_triplet = sparcv9-sun-solaris2.7
target_alias = sparcv9-sun-solaris2.7
target_triplet = sparcv9-sun-solaris2.7
AMDEP = 
AMTAR = ${SHELL} /home/sverker/agents/gmp/missing --run tar
AR = ar
AS = @AS@
AWK = gawk
CALLING_CONVENTIONS_OBJS = 
CC = gcc
CCAS = gcc -c
CPP = gcc -E
CXX = @CXX@
CXXCPP = @CXXCPP@
DEPDIR = .deps
DLLTOOL = @DLLTOOL@
EXEEXT = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
M4 = m4
MAINT = #
MAKEINFO = ${SHELL} /home/sverker/agents/gmp/missing --run makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = gmp
RANLIB = ranlib
SPEED_CYCLECOUNTER_OBJS = sparcv9.lo
STRIP = strip
U = 
VERSION = 3.1.1
gmp_srclinks =  mpn/inlines.c mpn/add_n.asm mpn/sub_n.asm mpn/mul_1.asm mpn/addmul_1.asm mpn/submul_1.asm mpn/lshift.asm mpn/rshift.asm mpn/diveby3.c mpn/divrem.c mpn/divrem_1.c mpn/divrem_2.c mpn/mod_1.c mpn/mod_1_rs.c mpn/pre_mod_1.c mpn/dump.c mpn/mul.c mpn/mul_fft.c mpn/mul_n.c mpn/mul_basecase.c mpn/sqr_basecase.c mpn/random.c mpn/random2.c mpn/sqrtrem.c mpn/get_str.c mpn/set_str.c mpn/scan0.c mpn/scan1.c mpn/popcount.c mpn/hamdist.c mpn/cmp.c mpn/perfsqr.c mpn/bdivmod.c mpn/gcd_1.c mpn/gcd.c mpn/gcdext.c mpn/tdiv_qr.c mpn/bz_divrem_n.c mpn/sb_divrem_mn.c mpn/jacbase.c gmp-mparam.h
install_sh = ./install-sh
mpn_objects =  inlines.lo add_n.lo sub_n.lo mul_1.lo addmul_1.lo submul_1.lo lshift.lo rshift.lo diveby3.lo divrem.lo divrem_1.lo divrem_2.lo mod_1.lo mod_1_rs.lo pre_mod_1.lo dump.lo mul.lo mul_fft.lo mul_n.lo mul_basecase.lo sqr_basecase.lo random.lo random2.lo sqrtrem.lo get_str.lo set_str.lo scan0.lo scan1.lo popcount.lo hamdist.lo cmp.lo perfsqr.lo bdivmod.lo gcd_1.lo gcd.lo gcdext.lo tdiv_qr.lo bz_divrem_n.lo sb_divrem_mn.lo jacbase.lo
mpn_objs_in_libgmp = mpn/mp_bases.lo mpn/inlines.lo mpn/add_n.lo mpn/sub_n.lo mpn/mul_1.lo mpn/addmul_1.lo mpn/submul_1.lo mpn/lshift.lo mpn/rshift.lo mpn/diveby3.lo mpn/divrem.lo mpn/divrem_1.lo mpn/divrem_2.lo mpn/mod_1.lo mpn/mod_1_rs.lo mpn/pre_mod_1.lo mpn/dump.lo mpn/mul.lo mpn/mul_fft.lo mpn/mul_n.lo mpn/mul_basecase.lo mpn/sqr_basecase.lo mpn/random.lo mpn/random2.lo mpn/sqrtrem.lo mpn/get_str.lo mpn/set_str.lo mpn/scan0.lo mpn/scan1.lo mpn/popcount.lo mpn/hamdist.lo mpn/cmp.lo mpn/perfsqr.lo mpn/bdivmod.lo mpn/gcd_1.lo mpn/gcd.lo mpn/gcdext.lo mpn/tdiv_qr.lo mpn/bz_divrem_n.lo mpn/sb_divrem_mn.lo mpn/jacbase.lo

# Copyright (C) 2000 Free Software Foundation, Inc.
#
# This file is part of the GNU MP Library.
#
# The GNU MP Library is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2.1 of the License, or (at your
# option) any later version.
#
# The GNU MP Library is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with the GNU MP Library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston,
# MA 02111-1307, USA.


AUTOMAKE_OPTIONS = gnu no-dependencies $(top_builddir)/ansi2knr

INCLUDES = -I$(top_srcdir)
LDADD = $(top_builddir)/libgmp.la

check_PROGRAMS = t-rand
TESTS = $(check_PROGRAMS)

EXTRA_PROGRAMS = findlc gen gen.static spect stat
gen_static_SOURCES = gen.c
gen_static_LDFLAGS = -static
findlc_LDADD = libstat.la
spect_LDADD = libstat.la
stat_LDADD = libstat.la

EXTRA_LTLIBRARIES = libstat.la
libstat_la_SOURCES = statlib.c zdiv_round.c
libstat_la_LIBADD = $(top_builddir)/libgmp.la -lm

EXTRA_DIST = gmpstat.h

CLEANFILES = $(EXTRA_PROGRAMS) $(EXTRA_LTLIBRARIES)
subdir = tests/rand
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 

DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LDFLAGS = 
LIBS = 
ANSI2KNR = $(top_builddir)/ansi2knr
libstat_la_LDFLAGS = 
libstat_la_DEPENDENCIES =  $(top_builddir)/libgmp.la
am_libstat_la_OBJECTS =  statlib$U.lo zdiv_round$U.lo
libstat_la_OBJECTS =  $(am_libstat_la_OBJECTS)
EXTRA_PROGRAMS =  findlc$(EXEEXT) gen$(EXEEXT) gen.static spect$(EXEEXT) \
stat$(EXEEXT)
check_PROGRAMS =  t-rand$(EXEEXT)
findlc_SOURCES = findlc.c
findlc_OBJECTS =  findlc$U.$(OBJEXT)
findlc_DEPENDENCIES =  libstat.la
findlc_LDFLAGS = 
gen_SOURCES = gen.c
gen_OBJECTS =  gen$U.$(OBJEXT)
gen_LDADD = $(LDADD)
gen_DEPENDENCIES =  $(top_builddir)/libgmp.la
gen_LDFLAGS = 
am_gen_static_OBJECTS =  gen$U.$(OBJEXT)
gen_static_OBJECTS =  $(am_gen_static_OBJECTS)
gen_static_LDADD = $(LDADD)
gen_static_DEPENDENCIES =  $(top_builddir)/libgmp.la
spect_SOURCES = spect.c
spect_OBJECTS =  spect$U.$(OBJEXT)
spect_DEPENDENCIES =  libstat.la
spect_LDFLAGS = 
stat_SOURCES = stat.c
stat_OBJECTS =  stat$U.$(OBJEXT)
stat_DEPENDENCIES =  libstat.la
stat_LDFLAGS = 
t_rand_SOURCES = t-rand.c
t_rand_OBJECTS =  t-rand$U.$(OBJEXT)
t_rand_LDADD = $(LDADD)
t_rand_DEPENDENCIES =  $(top_builddir)/libgmp.la
t_rand_LDFLAGS = 
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CFLAGS = -g -O2 -Wa,-xarch=v8plus -mcpu=v9
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
DIST_SOURCES =  $(libstat_la_SOURCES) findlc.c gen.c \
$(gen_static_SOURCES) spect.c stat.c t-rand.c
DIST_COMMON =  ChangeLog Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

GZIP_ENV = --best
depcomp = 
SOURCES = $(libstat_la_SOURCES) findlc.c gen.c $(gen_static_SOURCES) spect.c stat.c t-rand.c
OBJECTS = $(am_libstat_la_OBJECTS) findlc$U.$(OBJEXT) gen$U.$(OBJEXT) $(am_gen_static_OBJECTS) spect$U.$(OBJEXT) stat$U.$(OBJEXT) t-rand$U.$(OBJEXT)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu tests/rand/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:
$(top_builddir)/ansi2knr: $(top_builddir)/ansi2knr.$(OBJEXT)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) ansi2knr

$(top_builddir)/ansi2knr.$(OBJEXT):
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) ansi2knr.$(OBJEXT)


mostlyclean-kr:
	-rm -f *_.c

clean-kr:

distclean-kr:

maintainer-clean-kr:

libstat.la: $(libstat_la_OBJECTS) $(libstat_la_DEPENDENCIES)
	$(LINK)  $(libstat_la_LDFLAGS) $(libstat_la_OBJECTS) $(libstat_la_LIBADD) $(LIBS)

mostlyclean-checkPROGRAMS:

clean-checkPROGRAMS:
	-test -z "$(check_PROGRAMS)" || rm -f $(check_PROGRAMS)

distclean-checkPROGRAMS:

maintainer-clean-checkPROGRAMS:

findlc$(EXEEXT): $(findlc_OBJECTS) $(findlc_DEPENDENCIES)
	@rm -f findlc$(EXEEXT)
	$(LINK) $(findlc_LDFLAGS) $(findlc_OBJECTS) $(findlc_LDADD) $(LIBS)

gen$(EXEEXT): $(gen_OBJECTS) $(gen_DEPENDENCIES)
	@rm -f gen$(EXEEXT)
	$(LINK) $(gen_LDFLAGS) $(gen_OBJECTS) $(gen_LDADD) $(LIBS)

gen.static: $(gen_static_OBJECTS) $(gen_static_DEPENDENCIES)
	@rm -f gen.static
	$(LINK) $(gen_static_LDFLAGS) $(gen_static_OBJECTS) $(gen_static_LDADD) $(LIBS)

spect$(EXEEXT): $(spect_OBJECTS) $(spect_DEPENDENCIES)
	@rm -f spect$(EXEEXT)
	$(LINK) $(spect_LDFLAGS) $(spect_OBJECTS) $(spect_LDADD) $(LIBS)

stat$(EXEEXT): $(stat_OBJECTS) $(stat_DEPENDENCIES)
	@rm -f stat$(EXEEXT)
	$(LINK) $(stat_LDFLAGS) $(stat_OBJECTS) $(stat_LDADD) $(LIBS)

t-rand$(EXEEXT): $(t_rand_OBJECTS) $(t_rand_DEPENDENCIES)
	@rm -f t-rand$(EXEEXT)
	$(LINK) $(t_rand_LDFLAGS) $(t_rand_OBJECTS) $(t_rand_LDADD) $(LIBS)
.c.o:
	$(COMPILE) -c $<
.c.obj:
	$(COMPILE) -c `cygpath -w $<`
.c.lo:
	$(LTCOMPILE) -c -o $@ $<
findlc_.c: findlc.c $(ANSI2KNR)
	$(CPP) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) `if test -f $(srcdir)/findlc.c; then echo $(srcdir)/findlc.c; else echo findlc.c; fi` | sed 's/^# \([0-9]\)/#line \1/' | $(ANSI2KNR) > findlc_.c
gen_.c: gen.c $(ANSI2KNR)
	$(CPP) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) `if test -f $(srcdir)/gen.c; then echo $(srcdir)/gen.c; else echo gen.c; fi` | sed 's/^# \([0-9]\)/#line \1/' | $(ANSI2KNR) > gen_.c
spect_.c: spect.c $(ANSI2KNR)
	$(CPP) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) `if test -f $(srcdir)/spect.c; then echo $(srcdir)/spect.c; else echo spect.c; fi` | sed 's/^# \([0-9]\)/#line \1/' | $(ANSI2KNR) > spect_.c
stat_.c: stat.c $(ANSI2KNR)
	$(CPP) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) `if test -f $(srcdir)/stat.c; then echo $(srcdir)/stat.c; else echo stat.c; fi` | sed 's/^# \([0-9]\)/#line \1/' | $(ANSI2KNR) > stat_.c
statlib_.c: statlib.c $(ANSI2KNR)
	$(CPP) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) `if test -f $(srcdir)/statlib.c; then echo $(srcdir)/statlib.c; else echo statlib.c; fi` | sed 's/^# \([0-9]\)/#line \1/' | $(ANSI2KNR) > statlib_.c
t-rand_.c: t-rand.c $(ANSI2KNR)
	$(CPP) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) `if test -f $(srcdir)/t-rand.c; then echo $(srcdir)/t-rand.c; else echo t-rand.c; fi` | sed 's/^# \([0-9]\)/#line \1/' | $(ANSI2KNR) > t-rand_.c
zdiv_round_.c: zdiv_round.c $(ANSI2KNR)
	$(CPP) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) `if test -f $(srcdir)/zdiv_round.c; then echo $(srcdir)/zdiv_round.c; else echo zdiv_round.c; fi` | sed 's/^# \([0-9]\)/#line \1/' | $(ANSI2KNR) > zdiv_round_.c
findlc_.$(OBJEXT) findlc_.lo gen_.$(OBJEXT) gen_.lo spect_.$(OBJEXT) \
spect_.lo stat_.$(OBJEXT) stat_.lo statlib_.$(OBJEXT) statlib_.lo \
t-rand_.$(OBJEXT) t-rand_.lo zdiv_round_.$(OBJEXT) zdiv_round_.lo : \
$(ANSI2KNR)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir); \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; \
	srcdir=$(srcdir); export srcdir; \
	for tst in $(TESTS); do \
	  if test -f ./$$tst; then dir=./; \
	  elif test -f $$tst; then dir=; \
	  else dir="$(srcdir)/"; fi; \
	  if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	    all=`expr $$all + 1`; \
	    case " $(XFAIL_TESTS) " in \
	    *" $$tst "*) \
	      xpass=`expr $$xpass + 1`; \
	      failed=`expr $$failed + 1`; \
	      echo "XPASS: $$tst"; \
	    ;; \
	    *) \
	      echo "PASS: $$tst"; \
	    ;; \
	    esac; \
	  elif test $$? -ne 77; then \
	    all=`expr $$all + 1`; \
	    case " $(XFAIL_TESTS) " in \
	    *" $$tst "*) \
	      xfail=`expr $$xfail + 1`; \
	      echo "XFAIL: $$tst"; \
	    ;; \
	    *) \
	      failed=`expr $$failed + 1`; \
	      echo "FAIL: $$tst"; \
	    ;; \
	    esac; \
	  fi; \
	done; \
	if test "$$failed" -eq 0; then \
	  if test "$$xfail" -eq 0; then \
	    banner="All $$all tests passed"; \
	  else \
	    banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
	  fi; \
	else \
	  if test "$$xpass" -eq 0; then \
	    banner="$$failed of $$all tests failed"; \
	  else \
	    banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
	  fi; \
	fi; \
	dashes=`echo "$$banner" | sed s/./=/g`; \
	echo "$$dashes"; \
	echo "$$banner"; \
	echo "$$dashes"; \
	test "$$failed" -eq 0
info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am:
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am:
uninstall: uninstall-am
all-am: Makefile
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_STRIP_FLAG=-s install
installdirs:


mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	-rm -f Makefile.in
mostlyclean-am:  mostlyclean-compile mostlyclean-libtool mostlyclean-kr \
		mostlyclean-checkPROGRAMS mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-compile clean-libtool clean-kr clean-checkPROGRAMS \
		clean-tags clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-compile distclean-libtool distclean-kr \
		distclean-checkPROGRAMS distclean-tags \
		distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-kr maintainer-clean-checkPROGRAMS \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool mostlyclean-kr distclean-kr \
clean-kr maintainer-clean-kr mostlyclean-checkPROGRAMS \
distclean-checkPROGRAMS clean-checkPROGRAMS \
maintainer-clean-checkPROGRAMS tags mostlyclean-tags distclean-tags \
clean-tags maintainer-clean-tags distdir check-TESTS info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all install-strip \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


allprogs: $(EXTRA_PROGRAMS)

manual-test: gen$(EXEEXT) stat$(EXEEXT)
	@(echo -n '16i: '; ./gen -f mpz_urandomb -z 16 1000 \
		| ./stat -i 0xffff | grep '^[0-9]')
	@(echo -n '32i: '; ./gen -f mpz_urandomb -z 32 1000 \
		| ./stat -i 0xffffffff  | grep '^[0-9]')
	@(echo -n '33i: '; ./gen -f mpz_urandomb -z 33 1000 \
		| ./stat -i 0x1ffffffff  | grep '^[0-9]')
	@(echo -n '64i: '; ./gen -f mpz_urandomb -z 64 1000 \
		| ./stat -i 0xffffffffffffffff  | grep '^[0-9]')
	@(echo -n '128i: '; ./gen -f mpz_urandomb -z 128 1000 \
		| ./stat -i 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF | grep '^[0-9]')

	@(echo -n '16f: '; ./gen -f mpf_urandomb -z 16 1000 \
		| ./stat | grep '^[0-9]')
	@(echo -n '32f: '; ./gen -f mpf_urandomb -z 32 1000 \
		| ./stat | grep '^[0-9]')
	@(echo -n '33f: '; ./gen -f mpf_urandomb -z 33 1000 \
		| ./stat | grep '^[0-9]')
	@(echo -n '64f: '; ./gen -f mpf_urandomb -z 64 1000 \
		| ./stat | grep '^[0-9]')
	@(echo -n '128f: '; ./gen -f mpf_urandomb -z 128 1000 \
		| ./stat | grep '^[0-9]')

manual-bigtest: gen$(EXEEXT) stat$(EXEEXT)
	@(echo '16i: '; ./gen -f mpz_urandomb -z 16 50000 \
		| ./stat -2 1000 -i 0xffff | grep '^K[mp]')
	@(echo '32i: '; ./gen -f mpz_urandomb -z 32 50000 \
		| ./stat -2 1000 -i 0xffffffff | grep '^K[mp]')
	@(echo '33i: '; ./gen -f mpz_urandomb -z 33 50000 \
		| ./stat -2 1000 -i 0x1ffffffff | grep '^K[mp]')
	@(echo '64i: '; ./gen -f mpz_urandomb -z 64 50000 \
		| ./stat -2 1000 -i 0xffffffffffffffff  | grep '^K[mp]')
	@(echo '128i: '; ./gen -f mpz_urandomb -z 128 50000 \
		| ./stat -2 1000 -i 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF | grep '^K[mp]')

	@(echo '16f: '; ./gen -f mpf_urandomb -z 16 50000 \
		| ./stat -2 1000 | grep '^K[mp]')
	@(echo '32f: '; ./gen -f mpf_urandomb -z 32 50000 \
		| ./stat -2 1000 | grep '^K[mp]')
	@(echo '33f: '; ./gen -f mpf_urandomb -z 33 50000 \
		| ./stat -2 1000 | grep '^K[mp]')
	@(echo '64f: '; ./gen -f mpf_urandomb -z 64 50000 \
		| ./stat -2 1000 | grep '^K[mp]')
	@(echo '128f: '; ./gen -f mpf_urandomb -z 128 50000 \
		| ./stat -2 1000 | grep '^K[mp]')

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
