# WARNING: This Makefile is meant to be invoked via the AGENTS root Makefile.
# Direct invocation may not work.

SHELL = /bin/sh

AGENTS = ../agents

# Variables to pass to all submakes apart from installs, uninstalls, and
# cleans.
#VARS_TO_PASS = \


all:    
#	(cd analyser; \
#	 $(MAKE) $(MFLAGS) $(VARS_TO_PASS) VARS_TO_PASS='$(VARS_TO_PASS)' all)
#	(cd pevaluator; \
#	 $(MAKE) $(MFLAGS) $(VARS_TO_PASS) VARS_TO_PASS='$(VARS_TO_PASS)' all)
#	(cd saga; \
#	 $(MAKE) $(MFLAGS) $(VARS_TO_PASS) VARS_TO_PASS='$(VARS_TO_PASS)' all)


install:
#	(cd analyser; \
#	 $(MAKE) $(MFLAGS) $(INSTALL_VARS_TO_PASS) \
#		 INSTALL_VARS_TO_PASS='$(INSTALL_VARS_TO_PASS)' install)
#	(cd pevaluator; \
#	 $(MAKE) $(MFLAGS) $(INSTALL_VARS_TO_PASS) \
#		 INSTALL_VARS_TO_PASS='$(INSTALL_VARS_TO_PASS)' install)
#	(cd saga; \
#	 $(MAKE) $(MFLAGS) $(INSTALL_VARS_TO_PASS) \
#		 INSTALL_VARS_TO_PASS='$(INSTALL_VARS_TO_PASS)' install)


uninstall:
#	(cd analyser; \
#	 $(MAKE) $(MFLAGS) $(INSTALL_VARS_TO_PASS) \
#		 INSTALL_VARS_TO_PASS='$(INSTALL_VARS_TO_PASS)' uninstall)
#	(cd pevaluator; \
#	 $(MAKE) $(MFLAGS) $(INSTALL_VARS_TO_PASS) \
#		 INSTALL_VARS_TO_PASS='$(INSTALL_VARS_TO_PASS)' uninstall)
#	(cd saga; \
#	 $(MAKE) $(MFLAGS) $(INSTALL_VARS_TO_PASS) \
#		 INSTALL_VARS_TO_PASS='$(INSTALL_VARS_TO_PASS)' uninstall)


clean:
#	(cd analyser; \
#	 $(MAKE) $(MFLAGS) clean)
#	(cd pevaluator; \
#	 $(MAKE) $(MFLAGS) clean)
#	(cd saga; \
#	 $(MAKE) $(MFLAGS) clean)


realclean:	clean
#	(cd analyser; \
#	 $(MAKE) $(MFLAGS) realclean)
#	(cd pevaluator; \
#	 $(MAKE) $(MFLAGS) realclean)
#	(cd saga; \
#	 $(MAKE) $(MFLAGS) realclean)
